# Uncomment the next line to define a global platform for your project

platform :ios, '10.0'

use_frameworks!
target 'DictionaryTests' do
    pod 'OCMock', '~> 3.4'
end

target 'Dictionary' do
    pod 'ReactiveObjC', '~> 3.1'
end
